nanoframework/nanoframework.github.io

appveyor.yml
docfx.json
rename-nfproj-files.ps1

Signed-off-by: José Simões <jose.simoes@eclo.solutions>

Fix file rename issue

---

content/getting-started-guides/build-esp32.md

updated the documentation for ESP32 first time setup

---

content/building/cmake-tools-cmake-variants.md
content/getting-started-guides/build-esp32.md

Added comments and some requirements related to cmake-variants.json.

Cmake-variants notes

---

content/faq/working-with-esp32-targets.md
content/getting-started-guides/build-esp32.md

Detailed steps to follow and cross-reference from FAQ.

Adding hints about howto debug nanoCLR without special hardware

---

content/getting-started-guides/getting-started-managed.md

Additional description for ESP32 added

---

content/introduction/what-is-nanoframework.md

update broken link

---

content/esp32/esp32_pin_out.md

The current page didn't indicate the pin configurations could be changed.
Updated and added example on how to change pins.

Update ESP32 pin configuration page

---

azure-pipelines.yml

Adding System.Device.I2c docs to the /api doc
New System.Device.I2c repo where docs needs to be added

adding System.Device.I2c

---

content/getting-started-guides/getting-started-managed.md

- Fixes a blog post url in the docs

Fixed the link to a blog post

---

content/faq/automatic-firmware-updates.md
content/faq/index.md
content/toc.yml

- Add FAQ for automated updates

Add FAQ for automated updates

---

content/toc.yml

Fix link to ESP32 pin-out article

---

content/building/build-instructions.md

Added more info BUILD_VERSION.
Describe why and how to change the BUILD_VERSION.
- Improves docs.

Nanoclr build version matching

---

content/building/cmake-tools-cmake-variants.md

Added more info on BUILD_VERSION.
Just referencing other pages on this topic.
- Improves docs

BUILD_VERSION details

---

content/building/build-esp32.md

An alternative way to flash nanoCLR.bin.
- Improves docs.

Added info about flashing custom built firmware with nanoff tool.

---

content/architecture/unit-test.md
content/toc.yml

Unit-Test TOC fix and ref links

---

content/building/build-win32.md
content/toc.yml

Extracted from targets/win32/index.md and extended.
Exposing on main docs site could help contributors taking first steps on unit-test discovered bug fixing.
- Improvement

Add doc about building Win32 version

---

azure-pipelines.yml
content/toc.yml
content/unit-test/constraints-limitations.md
content/unit-test/using-test-platform.md
docfx.json

Fixing doc, adjusting Unit Test documentation
Fixing doc, adjusting Unit Test documentation
- Fixes issues with the TOC
- Adjusting Unit Test documentation

Fixing doc, adjusting Unit Test documentation

---

content/architecture/index.md
content/architecture/simplifications-and-trade-offs.md
content/toc.yml

- Add doc to keep track of the simplifications and trade-offs.
- Makes available details about these matters to help developers interested in these matters why some things work the way they do and the reasons behind it.

Add doc to keep track of the simplifications and trade-offs

---

content/building/using-dev-container.md
content/maintainers/container-maintenance.md
content/toc.yml

Adjusting documentation for dev containers
Adjusting documentation for dev containers
- With the new dev container model, adjusting the documentation.

Adjusting documentation for dev containers

---

content/getting-started-guides/getting-started-managed.md

I added a new bullet to include the action to update the mscorlib references in the Blink sample
This is fixing a problem with the Blink sample that was not able to Deploy without the update to the mscorlib class

Improving the Getting Started documentation

---

content/architecture/simplifications-and-trade-offs.md

- Add entry about generics in the platform limitations doc.
- Improving doc to have people aware of this.

Note about generics

---

devices/index.md
docfx.json
toc.yml

Split IoT.Device from API
- Split IoT.Device from API
- Create a new top toc entry for IoT.Device
- Remove samples from the build documentation.

Split IoT.Device from API

---

content/faq/index.md
content/faq/working-with-vs-extension.md

- Entry about COM exclusion list.

Add new FAQ entry for VS

---

azure-pipelines.yml

Adding SignalR infor intellisense comments
- Adding SignalR infor intellisense comments

Adding SignalR infor intellisense comments

---

azure-pipelines.yml

Add API doc for `System.Device.Adc`

---

azure-pipelines.yml

`nanoFramework.Aws.IoTCore.Devices` Missing from docs.

Add API docs for `nanoFramework.Aws.IoTCore.Devices`

---

azure-pipelines.yml

Fix device generation in pipeline
- Fix device generation in pipeline
- Renamed Devices.OneWire into Device.OneWire

Fix device generation in pipeline

---

content/unit-test/using-test-platform.md

See diff - it is self-explaining.
Enhacing the quality of the documentation and thus making it overall more readably.

Grammatical fix of a sentence

---

content/getting-started-guides/getting-started-managed.md

Fixing getting started to remove --preview
- Fixing getting started to remove --preview

Fixing getting started to remove --preview

---

content/contributing/cs-coding-style.md

Adjusting CSharp coding style
- Trying to make things more clear and updating the coding style guidelines.

Adjusting CSharp coding style

---

azure-pipelines.yml
content/architecture/class-libraries.md

- Add DI library to pipeline and class lib doc.

Add DI library

---

content/architecture/pe-file/AssemblyHeader.md
content/architecture/pe-file/ExceptionHandlerTableEntry.md
content/architecture/pe-file/ResourcesTableEntry.md
content/architecture/pe-file/TypeDefTableEntry.md
content/building/build-esp32.md
content/building/build-stm32.md
content/ti-simplelink/flash-nanoclr-cc32xx.md

* Pipeline was failing due to lint error.

Fix lint errors

---

content/faq/working-with-esp32-targets.md

- Add FAQ entry on how to decode ESP32 guru meditation error.

Add FAQ entry on how to decode ESP32 guru meditation error

---

content/building/cmake-presets.md

Add build option NF_FEATURE_BINARY_SERIALIZATION

---

content/building/cmake-presets.md

- Fix formatting of build options.
- Improving readability and consistency in formatting.

Fix formatting of build options

---

azure-pipelines.yml

- Add System.Runtime.Serialization to API.

Add System.Runtime.Serialization to API

---

api-filter-iot.yml
api-filter.yml
azure-pipelines.yml
docfx.json

- Installing docfx as .NET tool.

Work CI-CD

---

content/building/cmake-presets.md

- Improve explanation on RTM build option.

Improve explanation on RTM build option

---

content/architecture/class-libraries.md

- Improve explanation on what and where to change in CMake presets file when adding a new class lib.

Improve doc for adding new class lib about CMake presets

---

azure-pipelines.yml

- Update AZDO yaml with recently added libraries.

Add recently added libraries

---

azure-pipelines.yml

Fix improve doc links not working for dynamically generated pages
- Closes nanoFramework/Home#1324

Fix improve doc links not working for dynamically generated pages

---

content/building/build-esp32.md
content/building/build-in-visual-studio.md
content/building/build-instructions.md
content/building/build-nxp.md
content/building/build-stm32.md

- Fixes/Closes/Resolves nanoFramework/Home#NNNN

Update building folder urls to https

---

content/community-targets/GHI_FEZ_CERB40_NF.md
content/community-targets/I2M_ELECTRON_NF.md
content/community-targets/I2M_OXYGEN_NF.md
content/community-targets/NESHTEC-NeshNode.md
content/community-targets/ST_NUCLEO144_F412ZG_NF.md
content/community-targets/ST_NUCLEO64_F401RE_NF.md
content/community-targets/ST_NUCLEO64_F411RE_NF.md
content/community-targets/brainpad2.md
content/community-targets/mbn-quail.md
content/community-targets/netduino3-wifi.md
content/community-targets/pybstick2x.md
content/community-targets/st-nucleo144-f746zg.md
content/community-targets/st_nucleo144_f439zi.md
content/community-targets/stm32f4-discovery.md
content/community-targets/stm32f411-discovery.md
content/community-targets/ti-cc1352p1-launchxl.md
content/reference-targets/st-nucleo64-f091rc.md
content/reference-targets/ti-cc1352r1-launchxl.md

- Add missing labels with URL to firmware package on several targets.
- Rearrange several fw labels for consistent look across the various targets.

Fix fw packages labels

---

content/community-targets/GHI_FEZ_CERB40_NF.md
content/community-targets/st-nucleo144-f746zg.md
content/community-targets/st_nucleo144_f439zi.md
content/community-targets/stm32f4-discovery.md
content/community-targets/stm32f411-discovery.md
content/community-targets/ti-cc1352p1-launchxl.md

- Fixes/Closes/Resolves nanoFramework/Home#NNNN

Update community-targets folder urls to https

---

azure-pipelines.yml

Add missing UsbClient lib

---

azure-pipelines.yml

- Add more Gecko libs that were missing in the documentation.

Add more Gecko libs

---

content/building/cmake-presets.md
content/contributing/contributing-organizations.md
content/contributing/contributing-workflow.md
content/contributing/cs-coding-style.md
content/contributing/developing-native/arm-swo.md
content/contributing/developing-native/vscode-debug-instructions.md
content/licensing/chibios.md

Update contributing folder urls to https

---

azure-pipelines.yml
common.ps1

Pipeline improvements
- Fixes some issues
- Pipeline improvements with common functions

Pipeline improvements

---

content/getting-started-guides/gpio-explained.md

…ned.md
Fixed explanation at line 119 - "Pull-down is the pattern where the pin is connected though a resistor to the ground. That is our case 1."  Should say "That is our case 3", if I correctly understood it :)

Pull-down explanation typo - should say case 3 instead of 1

---

content/contributing/financial-sponsors.md
content/contributing/index.md
content/support/professional-support.md
docfx.json
templates/material/public/main.css

Adding black and light theme
- Adding black and light theme as quite some people asked for it!

Adding black and light theme

---

docfx.json

Add lang to website metadata

---

content/getting-started-guides/trouble-shooting-guide.md

Add instructions for people using other firmware before and got a E4004 error
- Help others to avoid this problem.
- Fixes content/getting-started-guides/trouble-shooting-guide

Update trouble-shooting-guide.md for nanoff ESP32 flash pitfall (E4004)

---

content/community-targets/netduino3-wifi.md

Update community-targets folder link

---

content/hal-pal/chibios/config-usb-virtual-com-port.md

Update hal-pal folder links

---

content/licensing/chibios.md

Update licensing folder links

---

content/architecture/nanoclr-stub-args.md

Fix spelling error "Tricsk" to "Tricks" in the Architecture section
Simple type-o fix.
- Fixes typeo

Fix spelling error "Tricsk" to "Tricks"

---

azure-pipelines.yml

Added nanoFramework.Device.Bluetooth to API documentation
Bluetooth API documentation seems to be missing

Added nanoFramework.Device.Bluetooth to API documentation

---

azure-pipelines.yml
content/getting-started-guides/index.md
content/getting-started-guides/trouble-shooting-guide.md
content/getting-started-guides/troubleshooting-device-connection.md
content/getting-started-guides/where-to-buy-devices.md

Improving troubleshooting and getting started links
Fix the TOC issue
- new devices need to be placed into manual boot mode
- added links on the overall beginner section where the troubleshooting is present
- fixes the TOC issue

Improving troubleshooting and getting started links and fixing TOC
